twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig'] # автоматическое форматирование всех форм Bootstrap-ом
when@test:
    twig:
        strict_variables: true
